version: '3.4'

services:

  keycloak_db:
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://archilab-infra:12201"
        
  keycloak:
    image: docker.nexus.archi-lab.io/archilab/coalbase-keycloak:${BUILD_ID}
    environment:
      - KEYCLOAK_USER=${COALBASE_KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${COALBASE_KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=login.archi-lab.io
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://archilab-infra:12201"
