version: '3.4'

services:
  keycloak_db:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
  keycloak:
    image: docker.nexus.archi-lab.io/archilab/coalbase-keycloak:${BUILD_ID}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
